#ifndef LEVIATHAN_ERROR_TYPES
#define LEVIATHAN_ERROR_TYPES

#ifndef ERROR_DELETED
#define ERROR_DELETED				-258
#endif
#ifndef ERROR_COMMON
#define ERROR_COMMON				5
#endif
#ifndef ERROR_OUTOFRANGE
#define ERROR_OUTOFRANGE			6
#endif
#ifndef ERROR_INVALIDPARAM
#define ERROR_INVALIDPARAM			7
#endif
#ifndef ERROR_CLASS_INSTANTIATE
#define ERROR_CLASS_INSTANTIATE		8
#endif
#ifndef ERROR_NOTENOUGH_PARAMS
#define ERROR_NOTENOUGH_PARAMS		9
#endif
#ifndef ERROR_WRONG_PARAMTYPE
#define ERROR_WRONG_PARAMTYPE		10
#endif
#ifndef ERROR_PARAM_GENERIC
#define ERROR_PARAM_GENERIC			11
#endif
#ifndef ERROR_EMPTY
#define ERROR_EMPTY					400
#endif
#ifndef ERROR_NOT_FOUND
#define ERROR_NOT_FOUND				404
#endif




#ifndef ERROR_SUCCEEDED
#define ERROR_SUCCEEDED							1
#endif
// script errors //
#ifndef ERROR_SCRIPT_INVALID_ID
#define ERROR_SCRIPT_INVALID_ID					0
#endif
#ifndef ERROR_SCRIPT_OBJECT_NOT_HIGHENOUGH
#define ERROR_SCRIPT_OBJECT_NOT_HIGHENOUGH		-2
#endif
#ifndef ERROR_SCRIPT_INVALID_PARAMETER
#define ERROR_SCRIPT_INVALID_PARAMETER			-3
#endif
#ifndef ERROR_SCRIPT_INVALID_GENERIC
#define ERROR_SCRIPT_INVALID_GENERIC			-4
#endif






#endif